micronaut:
  application:
    name: mymicronaut
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "classpath:static"

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost:5432/mymicronaut`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:mysecret}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    packages-to-scan:
      - 'mymicronaut.member'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      locations: classpath:db/migration